# Generated by Django 6.0.7 on 2026-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +250788111111', max_length=20),
        ),
    ]
