# Generated by Django 6.0.7 on 2026-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat shipping fee (RWF) added to orders from this store.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage tax/VAT applied to orders from this store, e.g. 18 for 18%.', max_digits=5),
        ),
    ]
